### ISSUE TITLE
linux系统中可以使用多个子进程加载数据，windows系统里是不可以的，在哪里调这个参数

### ISSUE THREAD

**Issue by Eric-yuye** [jrzaurin/pytorch-widedeep#128]
0%|          | 0/153 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\anaconda\envs\demand\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "F:\anaconda\envs\demand\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "F:\anaconda\envs\demand\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "F:\anaconda\envs\demand\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "F:\anaconda\envs\demand\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "F:\anaconda\envs\demand\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "F:\anaconda\envs\demand\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\sthq\code\demand_recommend\model\tabmlp\train.py", line 65, in <module>
    trainer.fit(
  File "F:\anaconda\envs\demand\lib\site-packages\pytorch_widedeep\utils\general_utils.py", line 61, in __call__
    return wrapped(*args, **kwargs)
  File "F:\anaconda\envs\demand\lib\site-packages\pytorch_widedeep\training\trainer.py", line 486, in fit
    for batch_idx, (data, targett, lds_weightt) in zip(t, train_loader):
  File "F:\anaconda\envs\demand\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "F:\anaconda\envs\demand\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "F:\anaconda\envs\demand\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "F:\anaconda\envs\demand\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "F:\anaconda\envs\demand\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\anaconda\envs\demand\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "F:\anaconda\envs\demand\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "F:\anaconda\envs\demand\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "F:\anaconda\envs\demand\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

进程已结束，退出代码 -1

**Comment by 5uperpalo** [comment]
hi @Eric-yuye , thank you for opening an issue, could you please provide a Minimal Reproducible Example so we could help you?

**Comment by wwzh0226** [comment]
Running the sample code using the windows system will report the above error, how to solve it?

**Comment by 5uperpalo** [comment]
hi @wwzh0226 @Eric-yuye the code is running also on windows machine, please see output. Please try to upgrade your packages:
```
PS C:\Windows\System32> python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import numpy as np
>>> import torch
>>> from sklearn.model_selection import train_test_split
>>>
>>> from pytorch_widedeep import Trainer
>>> from pytorch_widedeep.preprocessing import WidePreprocessor, TabPreprocessor
>>> from pytorch_widedeep.models import Wide, TabMlp, WideDeep
>>> from pytorch_widedeep.metrics import Accuracy
>>> from pytorch_widedeep.datasets import load_adult
>>>
>>> df = load_adult(as_frame=True)
>>> df["income_label"] = (df["income"].apply(lambda x: ">50K" in x)).astype(int)
>>> df.drop("income", axis=1, inplace=True)
>>> df_train, df_test = train_test_split(df, test_size=0.2, stratify=df.income_label)
>>>
>>> # Define the 'column set up'
>>> wide_cols = [
...     "education",
...     "relationship",
...     "workclass",
...     "occupation",
...     "native-country",
...     "gender",
... ]
>>> crossed_cols = [("education", "occupation"), ("native-country", "occupation")]
>>>
>>> cat_embed_cols = [
...     "workclass",
...     "education",
...     "marital-status",
...     "occupation",
...     "relationship",
...     "race",
...     "gender",
...     "capital-gain",
...     "capital-loss",
...     "native-country",
... ]
>>> continuous_cols = ["age", "hours-per-week"]
>>> target = "income_label"
>>> target = df_train[target].values
>>>
>>> # prepare the data
>>> wide_preprocessor = WidePreprocessor(wide_cols=wide_cols, crossed_cols=crossed_cols)
>>> X_wide = wide_preprocessor.fit_transform(df_train)
>>>
>>> tab_preprocessor = TabPreprocessor(
...     cat_embed_cols=cat_embed_cols, continuous_cols=continuous_cols  # type: ignore[arg-type]
... )
>>> X_tab = tab_preprocessor.fit_transform(df_train)
>>>
>>> # build the model
>>> wide = Wide(input_dim=np.unique(X_wide).shape[0], pred_dim=1)
>>> tab_mlp = TabMlp(
...     column_idx=tab_preprocessor.column_idx,
...     cat_embed_input=tab_preprocessor.cat_embed_input,
...     continuous_cols=continuous_cols,
... )
>>> model = WideDeep(wide=wide, deeptabular=tab_mlp)
>>>
>>> # train and validate
>>> trainer = Trainer(model, objective="binary", metrics=[Accuracy])
>>> trainer.fit(
...     X_wide=X_wide,
...     X_tab=X_tab,
...     target=target,
...     n_epochs=5,
...     batch_size=256,
... )
epoch 1: 100%|██████████████████████████████████| 153/153 [01:07<00:00,  2.26it/s, loss=0.414, metrics={'acc': 0.8023}]
epoch 2: 100%|███████████████████████████████████████████████████████████| 153/153 [01:38<00:00,  1.56it/s, loss=0.337, metrics={'acc': 0.8439}]
epoch 3: 100%|███████████████████████████████████████████████████████████| 153/153 [01:03<00:00,  2.41it/s, loss=0.319, metrics={'acc': 0.8532}]
epoch 4: 100%|████████████████████████████████████████████████████████████| 153/153 [01:13<00:00,  2.09it/s, loss=0.305, metrics={'acc': 0.858}]
epoch 5: 100%|███████████████████████████████████████████████████████████| 153/153 [01:10<00:00,  2.17it/s, loss=0.298, metrics={'acc': 0.8621}]
PS C:\Windows\System32> pip list
Package                            Version
---------------------------------- -------------------
-                                  tchdog
-atchdog                           0.10.3
-oblib                             0.17.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0
anaconda-project                   0.8.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.4
Babel                              2.8.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.9.3
bitarray                           1.6.1
bkcharts                           0.2
bleach                             3.2.1
blis                               0.7.9
bokeh                              2.2.3
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
catalogue                          2.0.8
certifi                            2020.6.20
cffi                               1.14.3
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.6
comtypes                           1.1.7
conda                              4.9.2
conda-build                        3.20.5
conda-package-handling             1.7.2
conda-verify                       3.4.2
confection                         0.0.4
contextlib2                        0.6.0.post1
cramjam                            2.6.2
cryptography                       3.1.1
cycler                             0.10.0
cymem                              2.0.7
Cython                             0.29.32
cytoolz                            0.11.0
dask                               2.30.0
dataclasses                        0.6
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.30.1
dnspython                          1.16.0
docopt                             0.6.2
docutils                           0.16
einops                             0.6.0
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
fastparquet                        2023.2.0
fett                               0.3.2
filelock                           3.0.12
flake8                             3.8.4
Flask                              1.1.2
fsspec                             0.8.3
fst-pso                            1.8.1
future                             0.18.2
FuzzyTM                            2.0.5
gensim                             4.3.0
gevent                             20.9.0
glob2                              0.7
greenlet                           0.4.17
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 2.0.0
imutils                            0.5.4
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.19.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              5.6.4
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             2.11.2
joblib                             1.2.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-core                       4.6.3
jupyterlab                         2.2.6
jupyterlab-pygments                0.1.2
jupyterlab-server                  1.2.0
keyring                            21.4.0
kiwisolver                         1.3.0
langcodes                          3.3.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.34.0
locket                             0.2.0
lxml                               4.6.1
MarkupSafe                         1.1.1
mat73                              0.45
matplotlib                         3.3.2
mccabe                             0.6.1
menuinst                           1.4.16
miniful                            0.0.6
mistune                            0.8.4
mkl-fft                            1.2.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.6.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
murmurhash                         1.0.9
navigator-updater                  0.2.1
nbclient                           0.5.1
nbconvert                          6.0.7
nbformat                           5.0.8
nest-asyncio                       1.4.2
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.1.4
numba                              0.51.2
numexpr                            2.8.4
numpy                              1.23.0
numpydoc                           1.1.0
olefile                            0.46
opencv-contrib-python              4.7.0.72
openpyxl                           3.0.5
packaging                          20.4
pandas                             1.5.3
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.7.0
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
pathy                              0.10.1
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.0.1
pip                                20.2.4
pkginfo                            1.6.1
pluggy                             0.13.1
ply                                3.11
preshed                            3.0.8
prometheus-client                  0.8.0
prompt-toolkit                     3.0.8
psutil                             5.7.2
py                                 1.9.0
pyarrow                            11.0.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydantic                           1.10.5
pydocstyle                         5.1.1
pyflakes                           2.2.0
pyFUME                             0.2.25
Pygments                           2.7.2
pylint                             2.6.0
pymongo                            3.11.2
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyreadline                         2.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             0.0.0
python-dateutil                    2.8.1
python-jsonrpc-server              0.3.4
python-language-server             0.35.1
pytorch-widedeep                   1.2.2
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          1.0.1
qtconsole                          4.7.7
QtPy                               1.9.0
regex                              2020.10.15
requests                           2.24.0
rope                               0.18.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
scikit-image                       0.17.2
scikit-learn                       1.2.1
scipy                              1.10.1
seaborn                            0.11.0
Send2Trash                         1.5.0
setuptools                         50.3.1.post20201107
simpful                            2.10.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.15.0
smart-open                         6.3.0
snooty-lextudio                    1.11.4.dev0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
spacy                              3.5.0
spacy-legacy                       3.0.12
spacy-loggers                      1.0.4
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.3.20
srsly                              2.4.5
statsmodels                        0.12.0
sympy                              1.6.2
tables                             3.6.1
tblib                              1.7.0
terminado                          0.9.1
testpath                           0.4.4
thinc                              8.1.7
threadpoolctl                      2.1.0
tifffile                           2020.10.1
toml                               0.10.1
toolz                              0.11.1
torch                              1.13.1
torchmetrics                       0.11.1
torchvision                        0.14.1
tornado                            6.0.4
tqdm                               4.50.2
traitlets                          5.0.5
typer                              0.7.0
typing-extensions                  4.5.0
ujson                              4.0.1
unicodecsv                         0.14.1
urllib3                            1.25.11
vboxapi                            1.0
wasabi                             1.1.1
watchdog                           1.0.2
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.3.7
xlwings                            0.20.8
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.4.0
zope.event                         4.5.0
zope.interface                     5.1.2
```

**Comment by 5uperpalo** [comment]
hi @Eric-yuye were you able to resolve your problems? may I close this issue?

**Comment by 5uperpalo** [comment]
@Eric-yuye, as there is no response I am closing the issue
